services:
  app:
    build: .
    container_name: ngo-app

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      - MONGO_URI=mongodb://mongo:27017/ngo-website

    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/resumes:/app/public/resumes

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: ngo-mongo

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
