apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: ngo

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: ""

  resources:
    requests:
      storage: 1Gi
