apiVersion: apps/v1
kind: Deployment

metadata:
  name: ngo-website
  namespace: ngo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ngo-website

  template:
    metadata:
      labels:
        app: ngo-website

    spec:
      containers:
      - name: ngo-website

        image: ngo-website:v2.2

        imagePullPolicy: Never

        ports:
        - containerPort: 3000

        env:

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ngo-config
              key: PORT

        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ngo-config
              key: BASE_URL

        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: ngo-secret
              key: MONGO_URI

        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: ngo-secret
              key: EMAIL_USER

        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: ngo-secret
              key: EMAIL_PASS

        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: ngo-secret
              key: SESSION_SECRET
