apiVersion: v1
kind: Secret
metadata:
  name: ngo-secret
  namespace: ngo

type: Opaque

data:
  EMAIL_USER: cHJhYmhhdHNha3JpZ2FsaUBnbWFpbC5jb20=
  EMAIL_PASS: anFiZ29ra2h2c3lzeXJqdQ==

stringData:
  MONGO_URI: mongodb://mongo-service:27017/ngoDB
  SESSION_SECRET: ngo-secret-key-123
